services:
  mongodb:
    image: mongo:latest
    container_name: song-api-mongo-db
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo/db:/data/db

volumes:
  data:
    driver: local
  configs:
    driver: local
